#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("BarcodeGeneratorDemo.Resource", IsApplication=true)]

namespace BarcodeGeneratorDemo
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Array
		{
			
			// aapt resource value: 0x7f050000
			public const int barcode_list = 2131034112;
			
			// aapt resource value: 0x7f050001
			public const int entries_list_languages = 2131034113;
			
			// aapt resource value: 0x7f050002
			public const int entryvalues_list_languages = 2131034114;
			
			static Array()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Array()
			{
			}
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Dimension
		{
			
			// aapt resource value: 0x7f060005
			public const int barcode_type_viewer_text_size = 2131099653;
			
			// aapt resource value: 0x7f060007
			public const int barcode_value_bitmap_text_size = 2131099655;
			
			// aapt resource value: 0x7f060006
			public const int barcode_value_viewer_text_size = 2131099654;
			
			// aapt resource value: 0x7f060004
			public const int barcode_viewer_image_view_margin = 2131099652;
			
			// aapt resource value: 0x7f060002
			public const int barcode_viewer_text_view_margin = 2131099650;
			
			// aapt resource value: 0x7f060003
			public const int barcode_viewer_text_view_min_height = 2131099651;
			
			// aapt resource value: 0x7f060000
			public const int edit_text_padding = 2131099648;
			
			// aapt resource value: 0x7f060008
			public const int icon_padding = 2131099656;
			
			// aapt resource value: 0x7f06000b
			public const int max_one_symbol_postal_barcode_width = 2131099659;
			
			// aapt resource value: 0x7f06000a
			public const int max_postal_barcode_height = 2131099658;
			
			// aapt resource value: 0x7f06000c
			public const int save_dialog_padding = 2131099660;
			
			// aapt resource value: 0x7f060009
			public const int settings_padding = 2131099657;
			
			// aapt resource value: 0x7f060001
			public const int value_description_layout_min_height = 2131099649;
			
			static Dimension()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Dimension()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f0a0024
			public const int action_about = 2131361828;
			
			// aapt resource value: 0x7f0a001f
			public const int action_accept = 2131361823;
			
			// aapt resource value: 0x7f0a0020
			public const int action_add = 2131361824;
			
			// aapt resource value: 0x7f0a001e
			public const int action_delete = 2131361822;
			
			// aapt resource value: 0x7f0a0022
			public const int action_delete_all = 2131361826;
			
			// aapt resource value: 0x7f0a001c
			public const int action_edit = 2131361820;
			
			// aapt resource value: 0x7f0a001d
			public const int action_save = 2131361821;
			
			// aapt resource value: 0x7f0a0021
			public const int action_scan = 2131361825;
			
			// aapt resource value: 0x7f0a0023
			public const int action_settings = 2131361827;
			
			// aapt resource value: 0x7f0a001b
			public const int barcode_backround_edit_text = 2131361819;
			
			// aapt resource value: 0x7f0a0019
			public const int barcode_color_layout = 2131361817;
			
			// aapt resource value: 0x7f0a0002
			public const int barcode_description_edit_text = 2131361794;
			
			// aapt resource value: 0x7f0a000e
			public const int barcode_description_text_view = 2131361806;
			
			// aapt resource value: 0x7f0a0008
			public const int barcode_error_correction_level_layout = 2131361800;
			
			// aapt resource value: 0x7f0a000a
			public const int barcode_error_correction_level_spinner = 2131361802;
			
			// aapt resource value: 0x7f0a001a
			public const int barcode_foreground_edit_text = 2131361818;
			
			// aapt resource value: 0x7f0a000d
			public const int barcode_generator_error_text_view = 2131361805;
			
			// aapt resource value: 0x7f0a0018
			public const int barcode_height_edit_text = 2131361816;
			
			// aapt resource value: 0x7f0a000c
			public const int barcode_image_view = 2131361804;
			
			// aapt resource value: 0x7f0a0016
			public const int barcode_size_layout = 2131361814;
			
			// aapt resource value: 0x7f0a0003
			public const int barcode_symbol_size_layout = 2131361795;
			
			// aapt resource value: 0x7f0a0005
			public const int barcode_symbol_size_spinner = 2131361797;
			
			// aapt resource value: 0x7f0a0007
			public const int barcode_symbol_size_spinner2 = 2131361799;
			
			// aapt resource value: 0x7f0a0001
			public const int barcode_value_edit_text = 2131361793;
			
			// aapt resource value: 0x7f0a0010
			public const int barcode_value_image_view = 2131361808;
			
			// aapt resource value: 0x7f0a000f
			public const int barcode_value_text_view = 2131361807;
			
			// aapt resource value: 0x7f0a000b
			public const int barcode_view_layout = 2131361803;
			
			// aapt resource value: 0x7f0a0017
			public const int barcode_width_edit_text = 2131361815;
			
			// aapt resource value: 0x7f0a0011
			public const int drawer_layout = 2131361809;
			
			// aapt resource value: 0x7f0a0009
			public const int error_correction_level_text_view = 2131361801;
			
			// aapt resource value: 0x7f0a0015
			public const int filename_edit_text = 2131361813;
			
			// aapt resource value: 0x7f0a0014
			public const int filepath_edit_text = 2131361812;
			
			// aapt resource value: 0x7f0a0000
			public const int icon_button = 2131361792;
			
			// aapt resource value: 0x7f0a0012
			public const int mainContentFrame = 2131361810;
			
			// aapt resource value: 0x7f0a0013
			public const int save_dialog_scroll_view = 2131361811;
			
			// aapt resource value: 0x7f0a0004
			public const int symbol_size_text_view = 2131361796;
			
			// aapt resource value: 0x7f0a0006
			public const int symbol_size_text_view2 = 2131361798;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int action_bar_layout = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int barcode_editor_layout = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int barcode_viewer_layout = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int main = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int save_dialog_layout = 2130903044;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Menu
		{
			
			// aapt resource value: 0x7f090000
			public const int barcode_viewer_menu = 2131296256;
			
			// aapt resource value: 0x7f090001
			public const int create_barcode_menu = 2131296257;
			
			// aapt resource value: 0x7f090002
			public const int main_action_bar = 2131296258;
			
			static Menu()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Menu()
			{
			}
		}
		
		public partial class Mipmap
		{
			
			// aapt resource value: 0x7f020000
			public const int accept = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int add = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int camera = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int delete = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int edit = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int icon = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int save = 2130837510;
			
			static Mipmap()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Mipmap()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f070007
			public const int about_barcode_button = 2131165191;
			
			// aapt resource value: 0x7f07000d
			public const int about_message = 2131165197;
			
			// aapt resource value: 0x7f07002e
			public const int acceptable_colors_label = 2131165230;
			
			// aapt resource value: 0x7f070003
			public const int add_barcode_button = 2131165187;
			
			// aapt resource value: 0x7f070000
			public const int app_name = 2131165184;
			
			// aapt resource value: 0x7f070021
			public const int auto_value = 2131165217;
			
			// aapt resource value: 0x7f07001d
			public const int aztec_error_correction_level_label = 2131165213;
			
			// aapt resource value: 0x7f07001c
			public const int aztec_layers_count_label = 2131165212;
			
			// aapt resource value: 0x7f070032
			public const int background_color_hint = 2131165234;
			
			// aapt resource value: 0x7f070031
			public const int background_color_text = 2131165233;
			
			// aapt resource value: 0x7f07000e
			public const int barcode_added_message = 2131165198;
			
			// aapt resource value: 0x7f070010
			public const int barcode_saved_message = 2131165200;
			
			// aapt resource value: 0x7f070011
			public const int barcode_type_unsupported_message = 2131165201;
			
			// aapt resource value: 0x7f070024
			public const int cancel_button = 2131165220;
			
			// aapt resource value: 0x7f07000a
			public const int copy_value_button = 2131165194;
			
			// aapt resource value: 0x7f07001a
			public const int default_error_correction_label = 2131165210;
			
			// aapt resource value: 0x7f07001b
			public const int default_error_correction_level_label = 2131165211;
			
			// aapt resource value: 0x7f070019
			public const int default_symbol_size_label = 2131165209;
			
			// aapt resource value: 0x7f070005
			public const int delete_all_barcode_button = 2131165189;
			
			// aapt resource value: 0x7f070014
			public const int delete_all_empty_message = 2131165204;
			
			// aapt resource value: 0x7f070013
			public const int delete_all_message = 2131165203;
			
			// aapt resource value: 0x7f070034
			public const int delete_button = 2131165236;
			
			// aapt resource value: 0x7f070035
			public const int delete_message = 2131165237;
			
			// aapt resource value: 0x7f070033
			public const int delete_title = 2131165235;
			
			// aapt resource value: 0x7f070016
			public const int dialog_title_list_languages = 2131165206;
			
			// aapt resource value: 0x7f07002c
			public const int divider_text = 2131165228;
			
			// aapt resource value: 0x7f070008
			public const int edit_button = 2131165192;
			
			// aapt resource value: 0x7f070017
			public const int enter_barcode_value_hint = 2131165207;
			
			// aapt resource value: 0x7f070018
			public const int enter_description_hint = 2131165208;
			
			// aapt resource value: 0x7f07000b
			public const int error_message_title = 2131165195;
			
			// aapt resource value: 0x7f070025
			public const int file_name_hint = 2131165221;
			
			// aapt resource value: 0x7f070026
			public const int file_path_hint = 2131165222;
			
			// aapt resource value: 0x7f070030
			public const int foreground_color_hint = 2131165232;
			
			// aapt resource value: 0x7f07002f
			public const int foreground_color_text = 2131165231;
			
			// aapt resource value: 0x7f070020
			public const int han_xin_symbol_version_label = 2131165216;
			
			// aapt resource value: 0x7f07002b
			public const int height_hint = 2131165227;
			
			// aapt resource value: 0x7f07002a
			public const int height_text = 2131165226;
			
			// aapt resource value: 0x7f07000f
			public const int language_change_message = 2131165199;
			
			// aapt resource value: 0x7f070009
			public const int ok_button = 2131165193;
			
			// aapt resource value: 0x7f07001f
			public const int pdf417_cols_label = 2131165215;
			
			// aapt resource value: 0x7f07001e
			public const int pdf417_rows_label = 2131165214;
			
			// aapt resource value: 0x7f07002d
			public const int pixels_text = 2131165229;
			
			// aapt resource value: 0x7f070023
			public const int save_button = 2131165219;
			
			// aapt resource value: 0x7f070022
			public const int save_title = 2131165218;
			
			// aapt resource value: 0x7f070004
			public const int scan_barcode_button = 2131165188;
			
			// aapt resource value: 0x7f070006
			public const int settings_barcode_button = 2131165190;
			
			// aapt resource value: 0x7f070027
			public const int size_label = 2131165223;
			
			// aapt resource value: 0x7f070001
			public const int title_barcode_type_selector = 2131165185;
			
			// aapt resource value: 0x7f070002
			public const int title_barcode_viewer = 2131165186;
			
			// aapt resource value: 0x7f070015
			public const int title_list_languages = 2131165205;
			
			// aapt resource value: 0x7f07000c
			public const int vintasoft_barcodes_url = 2131165196;
			
			// aapt resource value: 0x7f070012
			public const int vintasoft_scanner_not_found_message = 2131165202;
			
			// aapt resource value: 0x7f070029
			public const int width_hint = 2131165225;
			
			// aapt resource value: 0x7f070028
			public const int width_text = 2131165224;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f080000
			public const int OrangeActionBar = 2131230720;
			
			// aapt resource value: 0x7f080001
			public const int OrangeTheme = 2131230721;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
		
		public partial class Xml
		{
			
			// aapt resource value: 0x7f040000
			public const int settings_page = 2130968576;
			
			static Xml()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Xml()
			{
			}
		}
	}
}
#pragma warning restore 1591
